# Generated by Django 4.1.7 on 2023-03-28 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_status_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment_status',
            old_name='price',
            new_name='order_id',
        ),
        migrations.RemoveField(
            model_name='payment_status',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='payment_status',
            name='quantity',
        ),
    ]
