# Generated by Django 4.1.7 on 2023-03-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('cart_id', models.CharField(max_length=10)),
                ('created_date', models.CharField(max_length=100)),
                ('total_price', models.CharField(max_length=10)),
            ],
        ),
    ]
